config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only => [:index, :show]
  root "users#index"
  resources :messages, :only => [:create]
  resources :prices, :only => [:create, :index]
  resources :rooms, :only => [:create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :prices, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/total.rb
class Total < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages, dependent: :destroy
  has_many :prices, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, :only => [:create]

  def create
    if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
      @message = Message.create(params.require(:message).permit(:user_id, :content, :room_id).merge(:user_id => current_user.id))
      redirect_to "/rooms/#{@message.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :authenticate_user!, :only => [:create, :index]
  def create
    if Entry.where(:user_id => current_user.id, :room_id => params[:price][:room_id]).present?
      @price = Price.create(params.require(:price).permit(:user_id, :amount, :room_id).merge(:user_id => current_user.id))
      redirect_to "/rooms/#{@price.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @prices = Price.all
    @total_price = @prices.sum(:amount)
  end
  def show
    prices = Price.where(user_id: current_user)
    prices.sum(:amount)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @prices = @room.prices
      @price = Price.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/totals_controller.rb
class TotalsController < ApplicationController
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def index
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/totals_helper.rb
module TotalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OKANE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <h1>Chat App</h1>
    </div>
    <%= yield %>
  </body>
</html>

app/views/prices/index.html.erb
<%= @total_price %>

app/views/rooms/show.html.erb
<p class="member-p">参加者</p>
<div class="room-member">

<% @entries.each do |e| %>
  <h5><strong><a href="/users/<%= e.user.id %>"><%= e.user.email%>さん</a></strong></h5>
<% end %>
</div>

<% if @messages.present? || @prices.present? %>
  <div class="room-message">
    <h3>メッセージ</h3>
    <% @messages.each do |m| %>
      <p class="message-content"><strong><%= m.content %></strong>
      <small>by <a href="/users/<%= m.user_id %>"><%= m.user.email %>さん</a></small><%= m.created_at.strftime("%Y年%m月%d日 %H時%M分") %></p>

      <br>
    <% end %>
  </div>
  <div class="room-message">
    <h3>貸し借り</h3>
    <% @prices.each do |pr| %>
      <p class="message-content"><strong><%= pr.amount %></strong>
      <small>by <a href="/users/<%= pr.user_id %>"><%= pr.user.email %>さん</a></small><%= pr.created_at.strftime("%Y年%m月%d日 %H時%M分") %></p>
      <br>
    <% end %>

  </div>

<% else %>
  <h3 class="text-center">メッセージはまだありません</h3>
<% end %>

<%= form_for @message do |f| %>
  <p class="message-box"><%= f.text_field :content, :placeholder => "メッセージを入力して下さい" , :size => 70 %></p>
  <%= f.hidden_field :room_id, :value => @room.id %>

  <p class="message-submit"><%= f.submit "投稿する" %></p>
<% end %>
<%= form_for @price do |r| %>
  <p class="message-box"><%= r.text_field :amount, :placeholder => "金額を入力して下さい" , :size => 70 %></p>
  <%= r.hidden_field :room_id, :value => @room.id %>

  <p class="message-submit"><%= r.submit "投稿する" %></p>
<% end %>

<p class="backindexp"><%= link_to "ユーザー一覧に戻る", users_path %></p>

app/views/users/index.html.erb
<% if user_signed_in? %>
<h2>こんにちは　<%= current_user.email %>　さん</h2>
<div class="user-index">
  <p class="user-indexp"><span class="user-indexs">ユーザー一覧</span></p>
    <% @users.each do |u| %>
    <p class="usersp"><a class="usersa" href="/users/<%= u.id %>"><%= u.email %>さん</a></p>

    <% end %>
    <div class="index-logout"><%= link_to "ログアウト", destroy_user_session_path, :method => :delete %></div>
</div>
<% else %>
<div class="user-index-guest">
  <%= link_to "ユーザー登録する", new_user_registration_path %>
  <br>
  <%= link_to "ログインする", new_user_session_path %>
</div>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>

<h2><%= @user.email %></h2>

<% if @user.id == current_user.id %>
  <h2>マイページ</h2>
<% else %>
  <% if @isRoom == true %>
    <p class="chatstartp"><a class="chatstarta" href="/rooms/<%= @roomId %>">チャットをする</a>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, :value=> @user.id %>
      <% end %>
      <div class="chatstartb"><%= f.submit "チャットを始める" %></div>
    <% end %>
  <% end %>
<% end %>

<p class="backindexp"><%= link_to "ユーザー一覧に戻る", users_path %></p>